In [1]:
from sklearn.metrics import confusion_matrix, classification_report 
def scoreCalculator(predictor, attributes, labels):
    predicted = predictor.predict(attributes)
    errorScore = 0
    for guessIndex in range(len(predicted)):
        guess = predicted[guessIndex]
        actual = labels[guessIndex]
        if guess == 'hold' :
            errorScore += 0
#             if actual == 'hold':
#                 errorScore += 10
#             elif actual == 'long':
#                 errorScore += -5
#             else:
#                 errorScore += -5
        elif guess == 'long':
            if actual == 'short':
                errorScore += -15
            elif actual == 'hold':
                errorScore += -5
            else :#actual == 'long'
                errorScore += 20
        else: #short
            if actual == 'long':
                errorScore += -20
            elif actual == 'hold':
                errorScore += 0
            else: #actual == short
                errorScore += 20
    myMatrix = confusion_matrix(labels, predicted,normalize = 'all')     
    return  errorScore/len(predicted), myMatrix

In [2]:
def catBoostMaker(sectorDF,zScoreAnswer,fiveDayChangeAnswer,sector):
    subIndustryIndex = 0
    counter = -1
    for col in sectorDF.columns:
        counter += 1
        if col == 'GICS Sub Industry':
            subIndustryIndex = counter
            break
    masterList = sectorDF.values
    catIndicies = [subIndustryIndex]
    masterTrainList, masterTestList, zScoreTrainList, zScoreTestList, fiveDayChangeTrainList, fiveDayChangeTestList =\
    train_test_split(masterList,zScoreAnswer,fiveDayChangeAnswer,test_size = .3)

    trainPools = [Pool(data = masterTrainList, label = zScoreTrainList, cat_features = catIndicies),
    Pool(data = masterTrainList, label = fiveDayChangeTrainList, cat_features = catIndicies)]
    testPools = [Pool(data = masterTestList, label = zScoreTestList, cat_features = catIndicies),
    Pool(data = masterTestList, label = fiveDayChangeTestList, cat_features = catIndicies)]
    modelNames = ['ZScorePredictor','FiveDayPredictor']
    folderRoot = 'catPredictors/'

    print('Catboost:')
    for name, train, test in zip(modelNames, trainPools, testPools):
        print(name)
        model = CatBoostClassifier()
        model.fit(train, eval_set = test, logging_level = 'Silent')
        sector = sector.replace(' ', '_')
        model.save_model(folderRoot + name + sector + '.mlmodel')
        print('Accuracy: ', model.score(test))
        error, matrix = scoreCalculator(model, test,test.get_label())
        print('Error Score:', error)
        print('Confusion matrix:', matrix)


In [3]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import os
import pandas as pd
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
import json
import os

def sciKitPredictionMaker(sectorDF,zScoreAnswer,fiveDayChangeAnswer,sector):

    folderRoot = 'sciKitPredictors/'
    print('\nSci-Kit:')
    sectorDF.drop(columns = ['GICS Sub Industry'], inplace = True)
    masterList = sectorDF.values
    masterTrainList, masterTestList, zScoreTrainList, zScoreTestList, fiveDayChangeTrainList, fiveDayChangeTestList =\
    train_test_split(masterList,zScoreAnswer,fiveDayChangeAnswer,test_size = .3)
    
    
    hyperParamDict = {'accuracy': 0,
    'error_score': -np.inf,
    'min_samples_split': 0,
    'min_impurity_decrease': 0}
    min_samples_splitChoices = [20,50,100, 200]
    min_impurity_decreaseChoices = [0, 0.001, 0.01, 0.05, 0.1, 0.15]
    trainTestBundles = [['zScore', zScoreTrainList, zScoreTestList, hyperParamDict.copy()],
    ['fiveDay',fiveDayChangeTrainList, fiveDayChangeTestList, hyperParamDict.copy()]]

    for minSplit in min_samples_splitChoices:
        for minImpurity in min_impurity_decreaseChoices:
            for bundle in trainTestBundles:
                errorScoreList = []
                accuracyList = []
                for randState in range(3):
                    predictor = RandomForestClassifier(min_samples_split = minSplit, min_impurity_decrease = minImpurity,
                        random_state = randState, n_jobs = 2)
                    predictor.fit(masterTrainList, bundle[1])
                    predictions = predictor.predict(masterTestList)
                    predictionAccuracy = accuracy_score(bundle[2],predictions)
                    feature = pd.DataFrame(predictor.feature_importances_,
                                                        index = sectorDF.columns,
                                                        columns=['importance']).sort_values('importance', ascending=False)
                    errorScore, _ = scoreCalculator(predictor, masterTestList, zScoreTestList)
                    errorScoreList.append(errorScore)
                    accuracyList.append(predictionAccuracy)
                errorScore = sum(errorScoreList)/len(errorScoreList)
                predictionAccuracy = sum(accuracyList)/len(accuracyList)
                if errorScore > bundle[3]['error_score']:
                    bundle[3]['accuracy'] = predictionAccuracy
                    bundle[3]['error_score'] = errorScore
                    bundle[3]['min_samples_split'] = minSplit
                    bundle[3]['min_impurity_decrease'] = minImpurity
    print('Final result:')
    print(trainTestBundles[0][0], ' ', trainTestBundles[0][3])
    print(trainTestBundles[1][0], ' ',trainTestBundles[1][3])
    for bundle in trainTestBundles:
        predictor = RandomForestClassifier(min_samples_split = bundle[3]['min_samples_split'], 
        min_impurity_decrease = bundle[3]['min_impurity_decrease'], random_state = 1, n_jobs = 2)
        predictor.fit(masterTrainList, bundle[1])
        _, matrix = scoreCalculator(predictor, masterTestList, zScoreTestList)
        print(bundle[0], ' confusion matrix\n',matrix)
        sector = sector.replace(' ', '_')
        pickle.dump(predictor, open(folderRoot + bundle[0] + sector + '.pkl', 'wb'))

In [10]:
from catboost import CatBoostClassifier, Pool
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from collections import Counter


combinedDF = pd.read_csv('masterDF.csv', parse_dates = True)
combinedDF.drop(columns=['tmmrwChngAsPerc', 'Date', 'thisDayAveragePercentChange', 'thisDayPercentChangeStdev',
        'fiveDayWeightedAverage', 'tenDayWeightedAverage', 'fiveDaySlopeChange', 'tenDaySlopeChange', 
        'ticker', 'High', 'Low', 'Open', 'Close', 'Volume', 'fiveDayAverage', 'tenDayAverage'], inplace = True)
sectorList = combinedDF['GICS Sector'].copy().unique()
for sector in sectorList:
    print('Sector is: ', sector)
    sectorDF = combinedDF[combinedDF['GICS Sector'] == sector].copy()
    zScoreAnswer = sectorDF['zScoreOfChangeTmmrw']
    zScoreAnswer = zScoreAnswer.astype('float')
    zScoreAnswer = ['long' if x > .5 else 'short' if x < -.5 else 'hold' for x in zScoreAnswer ]
    fiveDayChangeAnswer = sectorDF['percentChangeInFiveDays']
    fiveDayChangeAnswer = ['long' if x > .02 else 'short' if x < -.02 else 'hold' for x in fiveDayChangeAnswer]
    
    sectorDF.drop(columns = ['zScoreOfChangeTmmrw','percentChangeInFiveDays', 'GICS Sector'], inplace = True)
    catBoostMaker(sectorDF,zScoreAnswer,fiveDayChangeAnswer, sector)
    sciKitPredictionMaker(sectorDF,zScoreAnswer,fiveDayChangeAnswer, sector)
    print('-------------------------------------------\n\n')

Sector is:  Health Care
Catboost:
ZScorePredictor
Accuracy:  0.4840010519856229
Error Score: 0.13412816691505217
Confusion matrix: [[0.4562111  0.01179101 0.00832822]
 [0.24033488 0.0171386  0.00876655]
 [0.23428596 0.01249233 0.01065135]]
FiveDayPredictor
Accuracy:  0.5536950995003068
Error Score: 0.25159989480143774
Confusion matrix: [[0.52682563 0.01731393 0.00398878]
 [0.24033488 0.02261769 0.00157798]
 [0.17191198 0.01117735 0.00425178]]

Sci-Kit:
Final result:
zScore   {'accuracy': 0.4821600771456123, 'error_score': 0.21952894421554014, 'min_samples_split': 20, 'min_impurity_decrease': 0}
fiveDay   {'accuracy': 0.5543672014260249, 'error_score': 0.12083223751497618, 'min_samples_split': 50, 'min_impurity_decrease': 0}
zScore  confusion matrix
 [[0.43762602 0.02073288 0.02086438]
 [0.22749189 0.02353818 0.01599895]
 [0.2171912  0.01538529 0.02117121]]
fiveDay  confusion matrix
 [[0.46190935 0.01551679 0.00179714]
 [0.24537565 0.02025072 0.00140265]
 [0.23779258 0.01415797 0.001797

fiveDay  confusion matrix
 [[0.4163139  0.05397265 0.0073266 ]
 [0.20677304 0.05177467 0.00537284]
 [0.20457506 0.0472973  0.00659394]]
-------------------------------------------


Sector is:  Industrials
Catboost:
ZScorePredictor
Accuracy:  0.4829649529857125
Error Score: 0.3171937965563561
Confusion matrix: [[0.43665283 0.01895836 0.01315789]
 [0.22576017 0.02765905 0.01245573]
 [0.22902674 0.01767615 0.01865307]]
FiveDayPredictor
Accuracy:  0.5422518011967273
Error Score: 0.5795884723409451
Confusion matrix: [[0.4760044  0.03855782 0.00903651]
 [0.21324338 0.05437172 0.00793748]
 [0.16271828 0.02625473 0.01187569]]

Sci-Kit:
Final result:
zScore   {'accuracy': 0.47728660398095, 'error_score': 0.3701103105792323, 'min_samples_split': 20, 'min_impurity_decrease': 0}
fiveDay   {'accuracy': 0.5401656693939024, 'error_score': 0.13727764887857696, 'min_samples_split': 50, 'min_impurity_decrease': 0}
zScore  confusion matrix
 [[0.41543534 0.02656002 0.02362926]
 [0.21574673 0.03349005 0.0